**
!artifacts/
!artifacts/configs/
!artifacts/configs/**
!artifacts/startup-scripts/
!artifacts/startup-scripts/**
!.cache/
!.cache/qemu_files/
!.cache/qemu_files/*.fd
!.cache/qemu_files/qemu-*.tar.xz

